### ISSUE TITLE
Recording audio causes Fieldbook to crash

### ISSUE THREAD

**Issue by bellerbrock** [trife/Field-Book#4]
Someone reported to us that audio recordings made with the fieldbook app were being overwritten by each subsequent recording. When testing to see if this was still an issue in the latest release, pressing record made the entire application crash. 
![screenshot_2015-09-30-15-20-59](https://cloud.githubusercontent.com/assets/11297346/10204161/41543f4a-6788-11e5-9a77-c62a3e9b0e1b.png)
![screenshot_2015-09-30-15-21-19](https://cloud.githubusercontent.com/assets/11297346/10204171/46edcc50-6788-11e5-82f8-fd0cb889f067.png)
this is on a Nexus seven, running Android version 5.1.1 and fieldbook v3.0.0

**Comment by trife** [comment]
I'll look into what might be making this happen. Can you try it again and choose the report option so that I can see the crash log?

**Comment by bellerbrock** [comment]
no problem, I just generated the error again and went with the report
option.

**Comment by trife** [comment]
Should be resolved with 57e78be684c93b3d58729fd24356f6f43f4d3f28. Have a few other changes to make and then I'll release an updated apk.
