### ISSUE TITLE
wrong value is exported for photo traits

### ISSUE THREAD

**Issue by bellerbrock** [trife/Field-Book#6]
It looks like photo traits are given the value recorded for the previous trait when they are exported in table format, rather than the photo's path. The database format has duplicate rows, the first with the same error, and the second with the correct path.

I ran into this issue on a Nexus 5X running fieldBook version 3.2.5, then saw it again when I switched to a Nexus 7 running 3.2.4. The import, .trt, and export files I was using are attached as a zip file. 
[export_error_files.zip](https://github.com/trife/Field-Book/files/604586/export_error_files.zip)

Assuming I'm not doing something wrong, would this be a simple fix? We'd like to use photo traits to start uploading pictures recorded with the fieldbook app to sgn databases.

**Comment by trife** [comment]
Can you also export your database and upload the two files that get exported to the database folder? That will let me diagnose if this is a bug that occurs during export or if it occurs during actual data collection. If you only collect a single image, does this same bug happen?

**Comment by bellerbrock** [comment]
No problem, here are the zipped files. After exporting the db, I reset the app, re-imported the field, recorded a couple of numeric traits and captured a single image. It looks like the same bug still happens on export.

[database_export.zip](https://github.com/trife/Field-Book/files/607793/database_export.zip)

**Comment by trife** [comment]
I think I tracked down the issue. A database modification didn't allow images to be loaded correctly. On my end, resetting the database and reimporting the field file resolved the issue. I'll reopen this if that doesn't work for you.
